# Generated by Django 5.2.6 on 2026-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('estado', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada')], default='available', max_length=20)),
            ],
        ),
    ]
