# Generated by Django 5.2.6 on 2026-04-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupadad')], default='available', max_length=20)),
            ],
        ),
    ]
